# Generated by Django 5.0.7 on 2024-07-29 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limonpay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card_number', models.CharField(max_length=20)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limonpay.merchant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limonpay.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhonePaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limonpay.merchant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limonpay.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
