# Generated by Django 5.0.7 on 2024-07-29 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limonpay', '0004_card_expiration_date_alter_card_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpaymenttransaction',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='limonpay.card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonepaymenttransaction',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='limonpay.card'),
            preserve_default=False,
        ),
    ]
